on: push
jobs:
  clear-key:
    uses: cmancone/clear-key-deployments/.github/workflows/test_and_deploy.yml@f8c3209919e1bc2f7770f63e49228d6d88092d96
    with:
      aws-producer-path: /credentials
      access-id: p-jiu4ebrbyalq
      migration-function-name: products-db-migration
