on: push
jobs:
  clear-key:
    permissions:
      id-token: write
      contents: read
    uses: cmancone/clear-key-deployments/.github/workflows/test_and_deploy.yml@c1212160f9b5e226d080fe422adc8c8a3adb0597
    with:
      aws-producer-path: /credentials
      access-id: p-jiu4ebrbyalq
