on: push
jobs:
  clear-key:
    permissions:
      id-token: write
      contents: read
    uses: cmancone/clear-key-deployments/.github/workflows/test_and_deploy.yml@3a185d6a87af696260973a43071fafee442cfed6
    with:
      aws-producer-path: /credentials
      access-id: p-jiu4ebrbyalq
