on: push
jobs:
  clear-key:
    permissions:
      id-token: write
      contents: read
    uses: cmancone/clear-key-deployments/.github/workflows/test_and_deploy.yml@main
    with:
      aws-producer-path: /path/to/aws/producer
      access-id: p-123456789012
      migration-function-name: products-db-migration
      migration-function-region: us-east-1
      run-database-migrations: false
